### ISSUE TITLE
issue with pillow

### ISSUE THREAD

**Issue by bobowolf** [taizilongxu/douban.fm#105]
OS: linuxmint 17.3
升级douban.fm到V0.4.11，提示
Can't roll back Pillow; was not uninstalled

我尝试 sudo pip uninstall pillow, 提示owned by OS.

另，最近刚更新linuxmint 到 17.3。 所以不太确定是那一边的问题。

谢谢。

**Comment by taizilongxu** [comment]
升级下, V0.4.12, 我把pillow去掉了, 看能运行吗

**Comment by bobowolf** [comment]
谢谢。```sudo pip install --upgrade douban.fm``` 提示 ```Can't roll back Pillow; was not uninstalled```。
```Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-VFa7_J-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/pillow```
先卸载 ```sudo pip uninstall douban.fm``` 再安装``` sudo pip install douban.fm ```没有报错，但是运行douban.fm 提示```cannot import name IncompleteRead```

**Comment by taizilongxu** [comment]
恩.., 默认python版本是2.7的吗?

**Comment by bobowolf** [comment]
```python --version ``` 
```Python 2.7.6```
```python3 --version```
```Python 2.7.6```

请教下，怎么看哪个是默认的？

**Comment by taizilongxu** [comment]
输入python 看打开的是3还是2

**Comment by bobowolf** [comment]
是2.7.5

**Comment by taizilongxu** [comment]
pip list | grep douban  看看是哪个版本?  0.4.12的应当已经完全去除了pillow

**Comment by bobowolf** [comment]
```douban.fm (0.4.12)```

**Comment by bobowolf** [comment]
运行douban.fm 错误提示是
```FATAL: cannot import name IncompleteRead```

**Comment by taizilongxu** [comment]
这个情况确实没见到过,  查了下 http://stackoverflow.com/questions/29282118/importerror-cannot-import-name-protocolerror/29282119#29282119  看看是pip的问题吗

**Comment by bobowolf** [comment]
可以啦, 运行
```
easy_install -U pip
```

谢谢

**Comment by taizilongxu** [comment]
想起来了, 启动的时候会调用pip的包检查下douban.fm的版本, 应当是这里的错误  :  )
