### ISSUE TITLE
歌曲名过长的情况，布局出了点问题

### ISSUE THREAD

**Issue by BruceZhang1993** [taizilongxu/douban.fm#107]
![1](https://cloud.githubusercontent.com/assets/6873988/11718885/235919fa-9f93-11e5-82bc-bfdf593e840f.png)

如图，第一行整体上移了一整行

建议：歌曲名过长，加滚动的效果～(>^ω^<)

**Comment by taizilongxu** [comment]
这个有点不太好弄,  主要是每个高亮都有转义字符

**Comment by BruceZhang1993** [comment]
@taizilongxu 要不就直接强行切歌曲名吧，一般都是歌名长了。。。
