### ISSUE TITLE
在OS X 10.10.5 上运行时出现如下错误

### ISSUE THREAD

**Issue by closears** [taizilongxu/douban.fm#108]
![hhe](https://cloud.githubusercontent.com/assets/8723784/11778081/3324cb84-a28d-11e5-8295-e1a67ceacddf.png)

**Comment by closears** [comment]
@taizilongxu

**Comment by taizilongxu** [comment]
`pip list | grep pyobjc`看看什么版本, 版本低的话`sudo pip update`一下试试
