### ISSUE TITLE
安装出现三个错误！

### ISSUE THREAD

**Issue by SmarmyWu** [taizilongxu/douban.fm#109]
错误提示：Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-BCUiq5/pyobjc-framework-CFNetwork
（有两个错误已经解决）
Python 2.7.11
pip 7.1.2
OSX EI capitan 10.11

怎么解决？

**Comment by taizilongxu** [comment]
`sudo pip install --upgrade setuptools` 试试这个?

**Comment by SmarmyWu** [comment]
SamdeMacBook-Air:~ root# pip install --upgrade setuptools
Collecting setuptools
  Downloading setuptools-19.0-py2.py3-none-any.whl (463kB)
    100% |████████████████████████████████| 466kB 801kB/s 
Installing collected packages: setuptools
  Found existing installation: setuptools 1.1.6
    Uninstalling setuptools-1.1.6:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/commands/install.py", line 311, in run
    root=options.root_path,
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/req/req_set.py", line 640, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/req/req_install.py", line 716, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/req/req_uninstall.py", line 125, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/utils/__init__.py", line 315, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 299, in move
    copytree(src, real_dst, symlinks=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 208, in copytree
    raise Error, errors
Error: [('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py', '/tmp/pip-l1VhfE-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py', "[Errno 1] Operation not permitted: '/tmp/pip-l1VhfE-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc', '/tmp/pip-l1VhfE-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc', "[Errno 1] Operation not permitted: '/tmp/pip-l1VhfE-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py', '/tmp/pip-l1VhfE-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py', "[Errno 1] Operation not permitted: '/tmp/pip-l1VhfE-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc', '/tmp/pip-l1VhfE-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc', "[Errno 1] Operation not permitted: '/tmp/pip-l1VhfE-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib', '/tmp/pip-l1VhfE-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib', "[Errno 1] Operation not permitted: '/tmp/pip-l1VhfE-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib'")]

还是不成功。

**Comment by taizilongxu** [comment]
这个不太清楚啦, 应当是pip的某些问题吧

**Comment by taizilongxu** [comment]
我这里
```
»»» pip list | grep pyobjc                                                                                                                   
pyobjc (3.0.4)
pyobjc-core (3.0.4)
pyobjc-framework-Accounts (3.0.4)
pyobjc-framework-AddressBook (3.0.4)
pyobjc-framework-AppleScriptKit (3.0.4)
pyobjc-framework-AppleScriptObjC (3.0.4)
pyobjc-framework-Automator (3.0.4)
pyobjc-framework-CalendarStore (3.0.4)
pyobjc-framework-CFNetwork (3.0.4)
pyobjc-framework-Cocoa (3.0.4)
pyobjc-framework-Collaboration (3.0.4)
pyobjc-framework-CoreData (3.0.4)
pyobjc-framework-CoreLocation (3.0.4)
pyobjc-framework-CoreText (3.0.4)
pyobjc-framework-CoreWLAN (3.0.4)
pyobjc-framework-DictionaryServices (3.0.4)
pyobjc-framework-DiskArbitration (3.0.4)
pyobjc-framework-EventKit (3.0.4)
pyobjc-framework-ExceptionHandling (3.0.4)
pyobjc-framework-FSEvents (3.0.4)
pyobjc-framework-InputMethodKit (3.0.4)
pyobjc-framework-InstallerPlugins (3.0.4)
pyobjc-framework-InstantMessage (3.0.4)
pyobjc-framework-LatentSemanticMapping (3.0.4)
pyobjc-framework-LaunchServices (3.0.4)
pyobjc-framework-Message (2.5.1)
pyobjc-framework-OpenDirectory (2.5.1)
pyobjc-framework-PreferencePanes (3.0.4)
pyobjc-framework-PubSub (3.0.4)
pyobjc-framework-QTKit (3.0.4)
pyobjc-framework-Quartz (3.0.4)
pyobjc-framework-ScreenSaver (3.0.4)
pyobjc-framework-ScriptingBridge (3.0.4)
pyobjc-framework-SearchKit (3.0.4)
pyobjc-framework-ServiceManagement (3.0.4)
pyobjc-framework-Social (3.0.4)
pyobjc-framework-StoreKit (3.0.4)
pyobjc-framework-SyncServices (3.0.4)
pyobjc-framework-SystemConfiguration (3.0.4)
pyobjc-framework-WebKit (3.0.4)
```

**Comment by SmarmyWu** [comment]
»»»pip list | grep pyobjc 
pyobjc-core (2.5.1)
pyobjc-framework-Accounts (2.5.1)
pyobjc-framework-AddressBook (2.5.1)
pyobjc-framework-AppleScriptKit (2.5.1)
pyobjc-framework-AppleScriptObjC (2.5.1)
pyobjc-framework-Automator (2.5.1)
pyobjc-framework-CFNetwork (2.5.1)
pyobjc-framework-Cocoa (2.5.1)
pyobjc-framework-Collaboration (2.5.1)
pyobjc-framework-CoreData (2.5.1)
pyobjc-framework-CoreLocation (2.5.1)
pyobjc-framework-CoreText (2.5.1)
pyobjc-framework-DictionaryServices (2.5.1)
pyobjc-framework-EventKit (2.5.1)
pyobjc-framework-ExceptionHandling (2.5.1)
pyobjc-framework-FSEvents (2.5.1)
pyobjc-framework-InputMethodKit (2.5.1)
pyobjc-framework-InstallerPlugins (2.5.1)
pyobjc-framework-InstantMessage (2.5.1)
pyobjc-framework-LatentSemanticMapping (2.5.1)
pyobjc-framework-LaunchServices (2.5.1)
pyobjc-framework-Message (2.5.1)
pyobjc-framework-OpenDirectory (2.5.1)
pyobjc-framework-PreferencePanes (2.5.1)
pyobjc-framework-PubSub (2.5.1)
pyobjc-framework-QTKit (2.5.1)
pyobjc-framework-Quartz (2.5.1)
pyobjc-framework-ScreenSaver (2.5.1)
pyobjc-framework-ScriptingBridge (2.5.1)
pyobjc-framework-SearchKit (2.5.1)
pyobjc-framework-ServiceManagement (2.5.1)
pyobjc-framework-Social (2.5.1)
pyobjc-framework-SyncServices (2.5.1)
pyobjc-framework-SystemConfiguration (2.5.1)
pyobjc-framework-WebKit (2.5.1)
这个是我的

**Comment by taizilongxu** [comment]
@SmarmyWu 那升级下pyobjc试试呢

**Comment by SmarmyWu** [comment]
已经解决，谢谢！

**Comment by AlexMusashi** [comment]
能否提供一下解决方法？我也遇到了这个问题

**Comment by huangshanglin** [comment]
出现同样的问题，请问怎么解决呀?
