### ISSUE TITLE
请问下Solution的问题

### ISSUE THREAD

**Issue by lmule** [taizilongxu/douban.fm#115]
请问下我输入邮箱、密码之后，后面还出来一个solution，但是我看不到什么图像，无法输入验证码，总提示我验证码不正确，请问怎么破？谢谢

**Comment by lmule** [comment]
我刚看了下您的源代码，发现验证码是存放在/tmp/captcha_pic.jpg的，我现在登录应该是没问题了，但是输入完验证码之后，回车出现这个错误：
![image](https://cloud.githubusercontent.com/assets/10286518/12150035/1899936e-b4e2-11e5-8853-07dce19bed5c.png)
请问是怎么回事呢？

**Comment by taizilongxu** [comment]
看样子是网络出问题， 删掉～/.doubanfm.token 重新试下登录

**Comment by lmule** [comment]
不好意思，继续骚扰

**Comment by lmule** [comment]
![image](https://cloud.githubusercontent.com/assets/10286518/12175336/935fbf32-b59c-11e5-81be-365ac84c51d5.png)
我卸载了，重新用pip-2.7安装的，还是有那个问题，并且没有找到你说的token文件

**Comment by taizilongxu** [comment]
网络能够连接吗?

**Comment by taizilongxu** [comment]
使用了什么vpn吗?  API报错, 看下 ~/.doubanfm.log输出啥
