### ISSUE TITLE
出现安装错误 mac os10.11.3

### ISSUE THREAD

**Issue by volfmath** [taizilongxu/douban.fm#120]
Collecting douban.fm
  Downloading douban.fm-0.4.13.tar.gz
Collecting termcolor (from douban.fm)
  Downloading termcolor-1.1.0.tar.gz
Collecting requests (from douban.fm)
  Downloading requests-2.9.1-py2.py3-none-any.whl (501kB)
    100% |████████████████████████████████| 503kB 34kB/s 
Requirement already satisfied (use --upgrade to upgrade): pyobjc-core in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC (from douban.fm)
Collecting pyobjc (from douban.fm)
  Downloading pyobjc-3.0.4.tar.gz
Collecting py2app>=0.8 (from pyobjc->douban.fm)
  Downloading py2app-0.9.tar.gz (1.7MB)
    100% |████████████████████████████████| 1.7MB 62kB/s 
Collecting pyobjc-framework-AddressBook==3.0.4 (from pyobjc->douban.fm)
  Downloading pyobjc-framework-AddressBook-3.0.4.tar.gz (51kB)
    100% |████████████████████████████████| 53kB 90kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-vDDKpZ/pyobjc-framework-AddressBook/setup.py", line 35, in <module>
        if fn.startswith('_AddressBook')
      File "pyobjc_setup.py", line 460, in setup
        **k
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 239, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 263, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 580, in resolve
        raise VersionConflict(dist,req) # XXX put more info here
    pkg_resources.VersionConflict: (pyobjc-core 2.5.1 (/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC), Requirement.parse('pyobjc-core>=3.0.4'))
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-vDDKpZ/pyobjc-framework-AddressBook

下面是我的环境

oujundeMacBook-Pro:~ oujun$ python -V
Python 2.7.10
oujundeMacBook-Pro:~ oujun$ which python
/usr/bin/python
oujundeMacBook-Pro:~ oujun$ pip list
altgraph (0.10.2)
bdist-mpkg (0.5.0)
bonjour-py (0.3)
Flask (0.10.1)
itsdangerous (0.24)
Jinja2 (2.8)
macholib (1.5.1)
MarkupSafe (0.23)
matplotlib (1.3.1)
modulegraph (0.10.4)
numpy (1.8.0rc1)
pip (8.0.2)
py2app (0.7.3)
pyobjc-core (2.5.1)
pyobjc-framework-Accounts (2.5.1)
pyobjc-framework-AddressBook (2.5.1)
pyobjc-framework-AppleScriptKit (2.5.1)
pyobjc-framework-AppleScriptObjC (2.5.1)
pyobjc-framework-Automator (2.5.1)
pyobjc-framework-CFNetwork (2.5.1)
pyobjc-framework-Cocoa (2.5.1)
pyobjc-framework-Collaboration (2.5.1)
pyobjc-framework-CoreData (2.5.1)
pyobjc-framework-CoreLocation (2.5.1)
pyobjc-framework-CoreText (2.5.1)
pyobjc-framework-DictionaryServices (2.5.1)
pyobjc-framework-EventKit (2.5.1)
pyobjc-framework-ExceptionHandling (2.5.1)
pyobjc-framework-FSEvents (2.5.1)
pyobjc-framework-InputMethodKit (2.5.1)
pyobjc-framework-InstallerPlugins (2.5.1)
pyobjc-framework-InstantMessage (2.5.1)
pyobjc-framework-LatentSemanticMapping (2.5.1)
pyobjc-framework-LaunchServices (2.5.1)
pyobjc-framework-Message (2.5.1)
pyobjc-framework-OpenDirectory (2.5.1)
pyobjc-framework-PreferencePanes (2.5.1)
pyobjc-framework-PubSub (2.5.1)
pyobjc-framework-QTKit (2.5.1)
pyobjc-framework-Quartz (2.5.1)
pyobjc-framework-ScreenSaver (2.5.1)
pyobjc-framework-ScriptingBridge (2.5.1)
pyobjc-framework-SearchKit (2.5.1)
pyobjc-framework-ServiceManagement (2.5.1)
pyobjc-framework-Social (2.5.1)
pyobjc-framework-SyncServices (2.5.1)
pyobjc-framework-SystemConfiguration (2.5.1)
pyobjc-framework-WebKit (2.5.1)
pyOpenSSL (0.13.1)
pyparsing (2.0.1)
python-dateutil (1.5)
pytz (2013.7)
scipy (0.13.0b1)
setuptools (1.1.6)
six (1.4.1)
Werkzeug (0.11.3)
wheel (0.29.0)
xattr (0.6.4)
zope.interface (4.1.1)

**Comment by songsanren** [comment]
1.升级pip到最新

2.安装pyobjc到最新

3.升级python 2到最新

4.安装
