### ISSUE TITLE
支持参数启动和发送信号

### ISSUE THREAD

**Issue by dawncold** [taizilongxu/douban.fm#121]
我把douban.fm放在了树莓派上，如果可以用参数启动或者发送信号的话，就可以通过外部的app或者微信来控制播放曲目、音量大小等

**Comment by taizilongxu** [comment]
发送信号可以理解，这个参数启动是指？

**Comment by dawncold** [comment]
比如启动douban.fm时可以指定红心兆赫还是其他什么的，可能可选的参数不多

*Sincerely,*
田震

**Comment by taizilongxu** [comment]
暂时完成了发送信号的功能, 

启动douban.fm 后会在本地建一个flask服务端

地址: `http://localhost:5000`

方法是`post`, key是`ch`

例如退出post一个`ch=q`的请求就可以了

**Comment by dawncold** [comment]
Great

我回去用用看

2016年2月27日星期六，hackerxu <notifications@github.com> 写道：

> 暂时完成了发送信号的功能,
>
> 启动douban.fm 后会在本地建一个flask服务端
>
> 地址: http://localhost:5000
>
> 方法是post, key是ch
>
> 例如退出post一个ch=q的请求就可以了
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/taizilongxu/douban.fm/issues/121#issuecomment-189565740>
> .
>


-- 
*Sincerely,*
田震
