### ISSUE TITLE
第一次使用时获取token失败，提示帐号不能为空

### ISSUE THREAD

**Issue by Rex-Diego** [taizilongxu/douban.fm#126]
第一次输入邮箱密码和验证码之后显示
➔ Solution: effect
帐号不能为空
(╯‵□′)╯︵┻━┻: 帐号不能为空

不知道怎么解决，可能是获取token的网页发生了变化？命令行下输入的email地址无法返回给响应位置了？

**Comment by SmarmyWu** [comment]
一样的问题：

$douban.fm
➔ Email: ********@**.com
➔ Password: 
➔ Solution: record
帐号不能为空
(╯‵□′)╯︵┻━┻: 帐号不能为空
➔ Email:

**Comment by qfengnh** [comment]
一样的问题

**Comment by heimi** [comment]
也遇到同样的问题

**Comment by taizilongxu** [comment]
看来是豆瓣API又改了, 需要时间重新分析下API

**Comment by heimi** [comment]
应该就是登录过程改了

**Comment by imaemo** [comment]
同样的问题，有朋友分析一下吗，我试着分析了一下也没弄出来
