### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by IvanWoo** [taizilongxu/douban.fm#131]
> Traceback (most recent call last):
>   File "/usr/local/bin/douban.fm", line 11, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python2.7/site-packages/doubanfm/douban.py", line 101, in main
>     router = Router()
>   File "/usr/local/lib/python2.7/site-packages/doubanfm/douban.py", line 47, in __init__
>     self.data = data.Data()
>   File "/usr/local/lib/python2.7/site-packages/doubanfm/data.py", line 23, in __init__
>     self.playlist = Playlist()
>   File "/usr/local/lib/python2.7/site-packages/doubanfm/model.py", line 40, in __init__
>     self._get_first_song()
>   File "/usr/local/lib/python2.7/site-packages/doubanfm/model.py", line 57, in _func
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python2.7/site-packages/doubanfm/model.py", line 82, in _get_first_song
>     song = douban.get_first_song()
>   File "/usr/local/lib/python2.7/site-packages/doubanfm/API/api.py", line 172, in get_first_song
>     return self.requests_url('n')
>   File "/usr/local/lib/python2.7/site-packages/doubanfm/API/api.py", line 163, in requests_url
>     raise APIError(err)
> doubanfm.exceptions.APIError: list index out of range

看起来和 #118 以及 #123 的问题非常类似，但又有所不同。
因为我是第一次登陆，所以并没有 ~/.doubanfm_token 文件。但我尝试了把 ~./doubanfm.log 以及 ~./doubanfm_config 删除之后再重新登录，还是 traceback 相同的信息。
有什么好的解决办法吗？
谢谢

**Comment by taizilongxu** [comment]
网页端 能登录吗？

**Comment by IvanWoo** [comment]
网页端没有问题。
