### ISSUE TITLE
douban.fm 403 forbidden

### ISSUE THREAD

**Issue by yrd241** [taizilongxu/douban.fm#132]
在一次程序卡住之后，
尝试删除~/.doubanfm_token 、 ~./doubanfm.log 、~./doubanfm_config等文件，
之后启动douban.fm 出现 403 forbidden.
并且我通过网页登录也是如此。
估计是我的IP被豆瓣给封了。。

请问，可以避免这个问题吗？

**Comment by taizilongxu** [comment]
应当是发起请求太多导致的， 不知道是什么情况卡住的?
