### ISSUE TITLE
字符界面建议使用curses库处理，对各类终端的兼容性会好很多

### ISSUE THREAD

**Issue by dbw9580** [taizilongxu/douban.fm#133]
嗯……目前在各种linux下的终端里的确工作地很好了……
只是在windows下用ConEmu的话还是会有显示上的问题（画面跳动，类似掉帧、颜色不正确等）
另外，curses库除了往各类终端上的显示东西之外还接管了键盘鼠标的输入，实在是很方便的。

我看到项目目前是自己造的轮子，相比用现成的curses库来说，兼容性还是略差，维护起来也麻烦……

附图：
![pic](https://i.imgur.com/jFwUjtv.png)

**Comment by taizilongxu** [comment]
原来用过curses， 兼容性应当不错， 但是没深入了解过，不知道能不能自由定位文字显示位置，还有每秒刷新显示时间？  

比如 这个 https://github.com/darknessomi/musicbox 用的curses ， 发现界面有点丑。。。

**Comment by taizilongxu** [comment]
curses 限制有点多啊， 很多功能都用不上，没太深入研究过curses，如果功能都满足的话，可以考虑迁移到curses  类似这个 https://github.com/darknessomi/musicbox ？
