### ISSUE TITLE
运行douban.fm 报语法错误，invalid syntax (pycookiecheat.py, line 27)

### ISSUE THREAD

**Issue by niuniuzh** [taizilongxu/douban.fm#149]
def clean(decrypted: bytes) -> str:
这个地方报错，语法错误，ubuntu,python2.7.12

**Comment by longgangfan** [comment]
导致这个错误的原因是pycookiecheat的版本>=0.4.0导致的，重新安装pycookiecheat 0.3.4就OK了！
pycookiecheat的版本>=0.4.0的版本适用于python3 。
