### ISSUE TITLE
Last.fm support

### ISSUE THREAD

**Issue by frostheart** [taizilongxu/douban.fm#23]
Please add last.fm scrobbling from douban.fm

**Comment by skyline75489** [comment]
Not having last.fm scrobbling support is basically the only reason why I made my own version... 
https://github.com/skyline75489/pyfm

**Comment by frostheart** [comment]
Working like a charm. Thank you. I really appreciate your work.

**Comment by taizilongxu** [comment]
@skyline75489  good

**Comment by taizilongxu** [comment]
Thanks for @skyline75489 .

V0.2.14 have update the last.fm

input:

    douban.fm last.fm

to config the last.fm
