### ISSUE TITLE
amixer unable to find simple control 'master' 0

### ISSUE THREAD

**Issue by amazon83** [taizilongxu/douban.fm#24]
Unable to adjust the volume, I'm using Raspberry pi user.

**Comment by amazon83** [comment]
amixer get master
amixer: Unable to find simple control 'master',0

I am using analogue not HDMI

**Comment by taizilongxu** [comment]
how about this https://github.com/taizilongxu/douban.fm/issues/22

**Comment by amazon83** [comment]
okie, for raspberry pi user douban.py inside find "Master" > "PCM" fix the bug.

**Comment by qfengnh** [comment]
有解决办法吗？

**Comment by taizilongxu** [comment]
```python
    def get_volume(self):
        if self.platform == 'Linux':
            volume = subprocess.check_output('amixer get Master | grep Mono: | cut -d " " -f 6', shell=True)
            return volume[1:-3]
        elif self.platform == 'Darwin':
            return subprocess.check_output('osascript -e "output volume of (get volume settings)"', shell=True)
        else:
            return

    # 调整音量大小
    def change_volume(self, increment):
        if increment == 1:
            volume = int(self.volume) + 5
        else:
            volume = int(self.volume) - 5
        if self.platform == 'Linux':
            subprocess.Popen('amixer set Master ' + str(volume) + '% >/dev/null 2>&1', shell=True)
        elif self.platform == 'Darwin':
            subprocess.Popen('osascript -e "set volume output volume ' + str(volume) + '"', shell=True)
        else:
            pass

```

因为声卡不一样,上面的同学是把"Master" 转换成"PCM"就可以了,你可以看看你的声卡是哪种,替换master应该就可以了

http://blog.csdn.net/juncoder/article/details/39269595 这里也有查看的方法

**Comment by qfengnh** [comment]
请告知一下具体要改哪个文件

**Comment by qfengnh** [comment]
我是使用 sudo pip install douban.fm安装的
所以请告知一下具体要改哪个文件

**Comment by qfengnh** [comment]
多谢 大神 指点，现已搞定

**Comment by royjiang** [comment]
hi, just found this post after i posted another issue for the same symptom :)

**Comment by k9gardner** [comment]
> okie, for raspberry pi user douban.py inside find "Master" > "PCM" fix the bug.

What does this statement mean? What do you mean by "inside" and "find", are these commands? Please give full syntax. I've been struggling with this for too long. Thanks.
