### ISSUE TITLE
voice volume adjustment with interactive command line does not work with Raspberry pi 

### ISSUE THREAD

**Issue by royjiang** [taizilongxu/douban.fm#26]
hi, installed douban.fm in my rpi , everything works fine except the volume  adjustment using "=" and "-" does not work , here is the fix i verified.

the reason is in the douban.py there is a line of code to associated to amixer "Master", but RPi does not use "Master" , it use "PCM" instead
 # 获取音量
    def get_volume(self):
        if self.platform == 'Linux':
            volume = subprocess.check_output('amixer get Master | grep Mono: | cut -d " " -f 6', 
shell=True)
            volume = volume[1:-3]
        elif self.platform == 'Darwin':
            volume = subprocess.check_output('osascript -e "output volume of (get volume setti
ngs)"', shell=True)
        else:
            volume = ''
        self.volume = volume

    # 调整音量大小
    def change_volume(self, increment):
        if increment == 1:
            volume = int(self.volume) + 5
        else:
            volume = int(self.volume) - 5
        if self.platform == 'Linux':
            subprocess.Popen('amixer set Master ' + str(volume) + '% >/dev/null 2>&1', shell=True
)

the way to fix it is just to replace the two words of  "Master" in the code with "PCM"

in my system , i got the path of the douban.py
 /usr/local/lib/python2.7/dist-packages/douban/douban.py

use an text editor to modify it, and restart your douban.fm, that's all.

after the fix , i got following, noted that i have "vol: 90%  →" now 

     Douban Fm \ retjiang   >>  64kbps  01:38  rate: ★ ★ ★ ★ ★   vol: 90%  →
  >  红心兆赫 ♥  Hotel California • Hotel California • Eagles 1976
     私人兆赫 
     华语 
     欧美 
     七零 
     八零 
     九零 
     粤语 
     摇滚 
     民谣 
     轻音乐 
     原声 
     爵士 
     电子 
     说唱 
     R&B  
     日语 
     韩语 
     女声 
     法语 
     古典 
     动漫 
     咖啡馆 
     圣诞 
     Sonos 乐满人家 
     豆瓣好歌曲 
     世界音乐 
     布鲁斯 
     新歌 
     雷鬼

**Comment by taizilongxu** [comment]
OK!Thanks very much,I will update in next version!:)
