### ISSUE TITLE
我如果装了两个不同的douban.fm，我要怎么选择我想要的那个启动？

### ISSUE THREAD

**Issue by ShiftWang** [taizilongxu/douban.fm#29]
[turingou/douban.fm](https://github.com/turingou/douban.fm)
[taizilongxu/douban.fm](https://github.com/taizilongxu/douban.fm)
这两个启动命令都一样啊，怎么办？

**Comment by taizilongxu** [comment]
卸掉一个~~

或者你可以 clone 这个项目,用

    $ python douban.py

运行
