### ISSUE TITLE
Exception Handling

### ISSUE THREAD

**Issue by Hexcles** [taizilongxu/douban.fm#36]
身在海外，和豆瓣的连接不稳定，比较经常遇到网络问题，这两天下来好几次遇到 Uncaught Exception 然后程序行为就不正常了。

打算整理一下代码，主要是实现一下更完善的错误处理机制。估计需要一段时间，而且可能会有比较大的改动。好了以后发 PR 上来。

**Comment by taizilongxu** [comment]
(*^__^*) 好的,改好后要学习学习

**Comment by Hexcles** [comment]
Work under progress: https://github.com/Hexcles/douban.fm/tree/exception-handling

Doing some testing now.

**Comment by Hexcles** [comment]
Closed by pull request #42
