### ISSUE TITLE
There is a problem in choosing sound_card. 

### ISSUE THREAD

**Issue by iwrose** [taizilongxu/douban.fm#39]
```
 try:
        if subprocess.check_output('amixer | grep PCM'):
            sound_card = "PCM"
    except:
        sound_card = "Master"
```

the line "if subprocess.check_output('amixer | grep PCM'):¨  should be modified to:
if subprocess.check_output('amixer | grep PCM',shell='true'):

otherwise: it will choose Master but not PCM in my raspberry pi.

**Comment by taizilongxu** [comment]
Thanks very much! I will update in next version.
