### ISSUE TITLE
在Ubuntu 14.04和 Mac OS  X 10.10环境下运行都没有声音

### ISSUE THREAD

**Issue by Jamesxu182** [taizilongxu/douban.fm#40]
在ubuntu14.04 和 Mac OS X 10.10环境下运行都没有声音

**Comment by taizilongxu** [comment]
确定安装了 mplayer 了吗?

**Comment by Jamesxu182** [comment]
好像没有，python边下载边播放的功能究竟是怎么实现的？

发自我的 iPhone

**Comment by taizilongxu** [comment]
mmh, 下载一下就好了.

是用 mplayer 直接播放 url 的

**Comment by Jamesxu182** [comment]
是这样啊，那应该很好实现吧。

发自我的 iPhone

**Comment by taizilongxu** [comment]
恩,基本就是 mplayer 封装了个 界面
