### ISSUE TITLE
【建议】

### ISSUE THREAD

**Issue by imsalze** [taizilongxu/douban.fm#43]
～1.请问声音调整幅度能改成5吗
～2.还有就是下一首的时候Ubuntu桌面通知会有延迟
～3.能设置默认的电台吗，每次重启后都是默认红心兆赫
～4.还有就是向上滚动的时候会有以下情况：http://i2.tietuku.com/bac084cf097018a9.png
～5.有时专辑名称过长之后会省略
～6.能不能自定义电台的显示，平常我只是听一下粤语什么的
～7.现在普通用户听的是192kbps，POR用户听的是320kbps，能否提升音质？

P.S.问题有点多哈，别介意，谢啦～

**Comment by taizilongxu** [comment]
1. 下一个版本将会改成 mplayer 内置声音,原来的音量调控基于系统的,并不精准,到时可以解决这个问题.
2. 待修改
3. 恩,这个建议非常好,默认电台设置倒不如使用上次退出时播放的电台,这样会简单些,也符合用户习惯.
4. 这个我没有发现哦,每次都出现吗?
5. 这个是以后要做的,暂时把这个功能放到后面做,就是横向滚动过长的歌曲名,专辑歌手
6. 收藏兆赫暂时不知道如何展示,有什么好的建议吗
7. 豆瓣默认是64kbps,pro 用户是192kbps, 提升音质有个方法就是像你推荐的使用网易云音乐的320高品质音质来代替原豆瓣 FM 的音乐,但是网易音乐版权问题还需要考虑考虑

**Comment by Hexcles** [comment]
如果方便的话，能否测试一下现在 github 上的最新版（master分支），至少应该修复了1、2两个问题

至于4，现在用的cli界面绘制方式的确是不支持在虚拟终端里滚屏的，和vim那种不一样。7的话豆瓣还没有推出 320kbps ，用其他地方的音源好像不大好。

3、5、6大概是TBD？

**Comment by id245** [comment]
回复Hexcles 
那这是怎么造成的--------------------
![2015-02-13 21 02 34](https://cloud.githubusercontent.com/assets/10728028/6187625/e37d7dd2-b3c3-11e4-842f-81d8a01b6366.png)

**Comment by taizilongxu** [comment]
看着好像终端里 clear 命令失效?

**Comment by id245** [comment]
![byzanz-demo](https://cloud.githubusercontent.com/assets/10728028/6188152/59dff2ca-b3c9-11e4-9412-da741efdbea5.gif)不知道能不能动图。。

**Comment by taizilongxu** [comment]
我原来用 ubuntu 没有出现过这种情况,刚才特意下了个虚拟机试了试,一切正常啊

**Comment by id245** [comment]
...那我也不知道了。。

**Comment by taizilongxu** [comment]
是不是终端特殊设置了?

**Comment by id245** [comment]
特殊设置指的是啥。

**Comment by taizilongxu** [comment]
终端环境是原生的吗

**Comment by id245** [comment]
是的

**Comment by taizilongxu** [comment]
今天才看到你说的第4个问题指的是用鼠标向上滚轮?

这个应当也有办法,终端里我记得有个光标定位的方法,我去找找看.

还有第7个问题,最近发现普通用户的64kbps长时间听是有点蛋疼,感觉PRO的192kbps的又有些不值,我在找找看有没有什么音源可以引入
