### ISSUE TITLE
Deal with missing mplayer (and might add support for mpg123)

### ISSUE THREAD

**Issue by Hexcles** [taizilongxu/douban.fm#45]
#44 & #38 seems related with the missing of mplayer. We should raise a more meaningful exception, failing loudly.

What is more, adding support for mpg123 might also be a good idea, since mpg123 is smaller and more people have it installed (as the dependency of other softwares).

I'll add support for mplayer2 and mpv as well. These twos are clone / next generation of mplayer and have similar interface.

**Comment by skyline75489** [comment]
Agreed. Support for mpg123 would be awesome.
