### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by Hexcles** [taizilongxu/douban.fm#72]
...不知道是不是调试的时候请求歌曲列表太频繁了，我现在所有请求都得到 403 Forbidden 。还是说是豆瓣关了这个接口？@taizilongxu 你能正常使用么？

**Comment by taizilongxu** [comment]
的确是调试的时候太频繁了,估计得等一个小时左右能解封吧

**Comment by Hexcles** [comment]
好吧…一小时能解封还好，差点打算发邮件给他们了…把这个issue关了吧 >_<
