### ISSUE TITLE
红心两边有乱码字符

### ISSUE THREAD

**Issue by hot123tea123** [taizilongxu/douban.fm#84]
那个试试是什么啊. 能不能直接删掉? 我用的是 lxterminal, 如果设置字体为思源黑体, 虽然没有了乱码, 但是因为不是等宽字体, 整个终端的字看起来都不行了. 如果能直接不显示那红心两边的字符就再好不过了.

![doubanfm-](https://cloud.githubusercontent.com/assets/2948593/9671462/ad7c4942-52c5-11e5-8508-138af742e986.png)

**Comment by taizilongxu** [comment]
红心两边没有字符的, 试试按234改变主题颜色有没有什么变化

**Comment by taizilongxu** [comment]
这个我也不太理解, 心形周围只有shell的颜色转义字符, 按理说其他地方的颜色转义正常, 心形周围也正常的, 第一次看到这个状况.

**Comment by hot123tea123** [comment]
转义字符的话, 应该不是字体问题吧. 只能算了.

**Comment by geekrainy** [comment]
同样的情况，ubuntu14.04(x64)

**Comment by ShiftWang** [comment]
同样的问题

**Comment by taizilongxu** [comment]
ls们终端都用的什么？

**Comment by ShiftWang** [comment]
自带的 http://i3.tietuku.com/2e244587551b1619.png

**Comment by geekrainy** [comment]
ubuntu自带终端。
![2015-09-08 08 54 37](https://cloud.githubusercontent.com/assets/7333266/9724303/8a09b43c-5607-11e5-8eef-d9f60471cf50.png)

**Comment by taizilongxu** [comment]
好的， 我今天测试一下

**Comment by heatfx** [comment]
fadora 22 x64； 桌面：xfce4； 使用终端：xfce4-terminal 0.6.3。 也有这个问题

**Comment by taizilongxu** [comment]
OK, 最近在重构项目,  重构完后会重新发布

**Comment by taizilongxu** [comment]
发布了V0.4.1版本, 我再ubuntu14.04试了下没问题了, 你们看看好了吗
