### ISSUE TITLE
运行后卡在Get Keys

### ISSUE THREAD

**Issue by liyzooes** [taizilongxu/douban.fm#93]
♥ Get local token - Username: N&N
♥ Get channel [ OK ]
♥ Get volume [ OK ]
♥ Get theme [ OK ]
♥ Get keys  [ OK ]

之后就没有反应了，不知道问题出在哪里？谢谢

**Comment by taizilongxu** [comment]
恩恩, 什么环境下的,  是否安装了mplayer?

**Comment by liyzooes** [comment]
kubuntu 15.04 ,装了mplayer

**Comment by taizilongxu** [comment]
哪个版本? 每次启动都这样吗

**Comment by liyzooes** [comment]
MPlayer2 2.0-728-g2c378c7-4 (C) 2000-2012 MPlayer Team
应该是这个吧，每次启动u都是这样的

**Comment by taizilongxu** [comment]
ennn, 删除一下~/里的配置文件看看呢(这三个.doubanfm.log     .doubanfm_config  .doubanfm_token)然后重新启动下看看

**Comment by taizilongxu** [comment]
你的douban.fm的版本是多少,  如果版本太低的话可以升级试试

**Comment by liyzooes** [comment]
这几天电脑不在身边所有没有看到呢，我晚上去看一下
